const swaggerAutogen = require('swagger-autogen')()
const env = require("dotenv");

const doc = {
    info: {
        version: "1.0.0",
        title: "Task Management API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: process.env.SERVER_HOST,
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "api_key",
            in: "header"
        },
        petstore_auth: {
            type: "oauth2",
            authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
            flow: "implicit",
            scopes: {
                read_pets: "read your pets",
                write_pets: "modify pets in your account"
            }
        }
    },
    definitions: {
        User: {
            name: "exampleUser",
            email: "example@gmail.com",
            password: "Password@123",
            phoneNumber: "12345678990",
        },
        Task: {
            description: "Task description",
            user_id: "ref of user id(referenced from login user)",
            completed: false
        },
    }
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['../index.js', '../controller/*.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('../index')           // Your project's root file
})